### ISSUE TITLE
search bar and create bar

### ISSUE THREAD

**Issue by joemcilheran** [tjgrist/Ad-At-The-Right-Time#2]
tried to make the "create search string" on the sales index page a partial instead of link. turns out a child action can't redirect, and when I made it not redirect, it simply disappeared after the first entry. would like to get this to work

**Comment by tjgrist** [comment]
@joemcilheran You may be able to solve this issue from this video. Guy had the same problem: Go to minute 46 -- https://www.youtube.com/watch?v=zWFoZb6EiwU

**Comment by joemcilheran** [comment]
thanks
